In [1]:
import numpy as np
import pandas as pd

In [2]:
data_preprocessed = pd.read_csv('kc_house_data_preprocessed.csv')
data_preprocessed.head()

year  month  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0  2014     10         3       1.00         1180      5650     1.0   
1  2014     12         3       2.25         2570      7242     2.0   
2  2015      2         2       1.00          770     10000     1.0   
3  2014     12         4       3.00         1960      5000     1.0   
4  2015      2         3       2.00         1680      8080     1.0   

   waterfront  condition  grade  sqft_above  sqft_basement  yr_built  \
0           0          3      7        1180              0      1955   
1           0          3      7        2170            400      1951   
2           0          3      6         770              0      1933   
3           0          5      7        1050            910      1965   
4           0          3      8        1680              0      1987   

   yr_renovated      lat     long  sqft_living15  sqft_lot15     price  
0             0  47.5112 -122.257           1340        5650  221900.0  
1          1991  47.7210 -122.319           1690        7639  538000.0  
2             0  47.7379 -122.233           2720        8062  180000.0  
3             0  47.5208 -122.393           1360        5000  604000.0  
4             0  47.6168 -122.045           1800        7503  510000.0

In [3]:
data_preprocessed.describe()

year         month      bedrooms     bathrooms   sqft_living  \
count  21613.000000  21613.000000  21613.000000  21613.000000  21613.000000   
mean    2014.322954      6.574423      3.370842      2.114757   2079.899736   
std        0.467616      3.115308      0.930062      0.770163    918.440897   
min     2014.000000      1.000000      0.000000      0.000000    290.000000   
25%     2014.000000      4.000000      3.000000      1.750000   1427.000000   
50%     2014.000000      6.000000      3.000000      2.250000   1910.000000   
75%     2015.000000      9.000000      4.000000      2.500000   2550.000000   
max     2015.000000     12.000000     33.000000      8.000000  13540.000000   

           sqft_lot        floors    waterfront     condition         grade  \
count  2.161300e+04  21613.000000  21613.000000  21613.000000  21613.000000   
mean   1.510697e+04      1.494309      0.007542      3.409430      7.656873   
std    4.142051e+04      0.539989      0.086517      0.650743      1.175459   
min    5.200000e+02      1.000000      0.000000      1.000000      1.000000   
25%    5.040000e+03      1.000000      0.000000      3.000000      7.000000   
50%    7.618000e+03      1.500000      0.000000      3.000000      7.000000   
75%    1.068800e+04      2.000000      0.000000      4.000000      8.000000   
max    1.651359e+06      3.500000      1.000000      5.000000     13.000000   

         sqft_above  sqft_basement      yr_built  yr_renovated           lat  \
count  21613.000000   21613.000000  21613.000000  21613.000000  21613.000000   
mean    1788.390691     291.509045   1971.005136     84.402258     47.560053   
std      828.090978     442.575043     29.373411    401.679240      0.138564   
min      290.000000       0.000000   1900.000000      0.000000     47.155900   
25%     1190.000000       0.000000   1951.000000      0.000000     47.471000   
50%     1560.000000       0.000000   1975.000000      0.000000     47.571800   
75%     2210.000000     560.000000   1997.000000      0.000000     47.678000   
max     9410.000000    4820.000000   2015.000000   2015.000000     47.777600   

               long  sqft_living15     sqft_lot15         price  
count  21613.000000   21613.000000   21613.000000  2.161300e+04  
mean    -122.213896    1986.552492   12768.455652  5.400881e+05  
std        0.140828     685.391304   27304.179631  3.671272e+05  
min     -122.519000     399.000000     651.000000  7.500000e+04  
25%     -122.328000    1490.000000    5100.000000  3.219500e+05  
50%     -122.230000    1840.000000    7620.000000  4.500000e+05  
75%     -122.125000    2360.000000   10083.000000  6.450000e+05  
max     -121.315000    6210.000000  871200.000000  7.700000e+06

### Declaring the dependant and independent variables

In [4]:
x = data_preprocessed.iloc[:,:-1]
y = data_preprocessed['price']

### Standardizing

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
scaler = StandardScaler()

In [7]:
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [8]:
x_scaled = scaler.transform(x)

In [9]:
x_scaled

array([[-0.69065478,  1.09962055, -0.39873715, ..., -0.30607896,
        -0.9433552 , -0.26071541],
       [-0.69065478,  1.74162654, -0.39873715, ..., -0.74634143,
        -0.43268619, -0.18786773],
       [ 1.44790136, -1.46840343, -1.47395936, ..., -0.13565477,
         1.07013975, -0.17237524],
       ...,
       [-0.69065478, -0.18439144, -1.47395936, ..., -0.60432128,
        -1.41025258, -0.39414129],
       [ 1.44790136, -1.78940643, -0.39873715, ...,  1.02891048,
        -0.8412214 , -0.42051149],
       [-0.69065478,  1.09962055, -1.47395936, ..., -0.60432128,
        -1.41025258, -0.41794772]])

### Creating Linear Regression

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
reg = LinearRegression()
reg.fit(x_scaled, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
reg.coef_

array([ 1.80793164e+04,  4.27471647e+03, -3.55232037e+04,  3.36577685e+04,
       -5.39756590e+17,  6.74685534e+03,  2.25953311e+03,  6.38612407e+04,
        2.13647804e+04,  1.19352830e+05,  4.86659037e+17,  2.60095992e+17,
       -7.67030141e+04,  1.00997106e+04,  7.57261937e+04, -1.98432059e+04,
        2.69281814e+04, -1.05088720e+04])

In [13]:
reg.intercept_

540147.2008267322

### Creating summary table

In [14]:
x.columns.values

array(['year', 'month', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'lat',
       'long', 'sqft_living15', 'sqft_lot15'], dtype=object)

In [15]:
reg_summary = pd.DataFrame([['Intercept'], ['year'], ['month'], ['bedrooms'], ['bathrooms'], ['sqft_living'],
       ['sqft_lot'], ['floors'], ['waterfront'], ['condition'], ['grade'],
       ['sqft_above'], ['sqft_basement'], ['yr_built'], ['yr_renovated'], ['lat'],
       ['long'], ['sqft_living15'], ['sqft_lot15']], columns=['Features'])
reg_summary['Coefficients'] = reg.intercept_, reg.coef_[0], reg.coef_[1], reg.coef_[2], reg.coef_[3], reg.coef_[4], reg.coef_[5], reg.coef_[6], reg.coef_[7], reg.coef_[8], reg.coef_[9], reg.coef_[10], reg.coef_[11], reg.coef_[12], reg.coef_[13], reg.coef_[14], reg.coef_[15], reg.coef_[16], reg.coef_[17]
reg_summary

Features  Coefficients
0       Intercept  5.401472e+05
1            year  1.807932e+04
2           month  4.274716e+03
3        bedrooms -3.552320e+04
4       bathrooms  3.365777e+04
5     sqft_living -5.397566e+17
6        sqft_lot  6.746855e+03
7          floors  2.259533e+03
8      waterfront  6.386124e+04
9       condition  2.136478e+04
10          grade  1.193528e+05
11     sqft_above  4.866590e+17
12  sqft_basement  2.600960e+17
13       yr_built -7.670301e+04
14   yr_renovated  1.009971e+04
15            lat  7.572619e+04
16           long -1.984321e+04
17  sqft_living15  2.692818e+04
18     sqft_lot15 -1.050887e+04

### Making predictions

In [19]:
reg.predict(x_scaled)

array([248497.91786655, 749448.38726419, 371465.91459094, ...,
       144374.10934176, 383341.89768739, 152575.69995853])

In [33]:
data_predict = data_preprocessed.copy()

In [34]:
data_predict['predicted_price'] = reg.predict(x_scaled)

In [35]:
data_predict['diff_percent'] = ((data_predict['predicted_price'] - data_predict['price'])/ data_predict['predicted_price']) * 100

In [38]:
data_predict = data_predict.iloc[:,-3:]
data_predict.head(25).round(2)

price  predicted_price  diff_percent
0    221900.0        248497.92         10.70
1    538000.0        749448.39         28.21
2    180000.0        371465.91         51.54
3    604000.0        490514.65        -23.14
4    510000.0        472790.55         -7.87
5   1225000.0       1532982.37         20.09
6    257500.0        227766.93        -13.05
7    291850.0        218239.16        -33.73
8    229500.0        390180.00         41.18
9    323000.0        279635.33        -15.51
10   662500.0        885434.07         25.18
11   468000.0        440463.18         -6.25
12   310000.0        540964.95         42.69
13   400000.0        316295.81        -26.46
14   530000.0        610316.59         13.16
15   650000.0        851381.48         23.65
16   395000.0        413861.38          4.56
17   485000.0        522300.66          7.14
18   189000.0        287329.17         34.22
19   230000.0        195022.64        -17.94
20   385000.0        475538.21         19.04
21  2000000.0        931866.71       -114.62
22   285000.0        351354.85         18.89
23   252700.0         99350.91       -154.35
24   329000.0        538255.98         38.88

In [39]:
data_predict.describe()

price  predicted_price  diff_percent
count  2.161300e+04     2.161300e+04  21613.000000
mean   5.400881e+05     5.400933e+05     -6.337539
std    3.671272e+05     3.050018e+05    987.815223
min    7.500000e+04    -6.070420e+05 -36994.497204
25%    3.219500e+05     3.388224e+05    -19.176032
50%    4.500000e+05     4.906364e+05      2.589924
75%    6.450000e+05     6.842178e+05     19.325428
max    7.700000e+06     3.323957e+06  88091.483930